apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.11.0
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  tag: v1.134.0
                env:
                  REDIS_HOSTNAME: 'immich-valkey'
                  IMMICH_MACHINE_LEARNING_URL: 'http://immich-machine-learning:3003'
                  DB_HOSTNAME: "immich-postgres-rw"
                  DB_USERNAME: "immich"
                  DB_PASSWORD: "changeme123"
                  DB_DATABASE_NAME: "immich"
        immich:
          persistence:
            library:
              existingClaim: immich-pvc
        valkey:
          enabled: true
        server:
          enabled: true
        machine-learning:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
