apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/immich-app/immich-charts
      chart: immich
      targetRevision: 0.13.1
      helm:
        valuesObject:
          controllers:
            main:
              containers:
                main:
                  image:
                    tag: v3.0.1
                  env:
          	    HOST:
                      valueFrom:
                        fieldRef:
                          fieldPath: status.podIP
                    REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
                    IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
                    DB_HOSTNAME: "immich-postgres-rw"
                    DB_USERNAME: "immich"
                    DB_PASSWORD:
                      valueFrom:
                        secretKeyRef:
                          name: immich-db-credentials
                          key: password
                    DB_DATABASE_NAME: "immich"
          immich:
            persistence:
              library:
                existingClaim: immich-pvc
          valkey:
            enabled: true
          server:
            enabled: true
          machine-learning:
            enabled: false
    - repoURL: https://github.com/Jeffrie-04/homelab.git
      targetRevision: main
      path: apps/immich
      directory:
        exclude: 'values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
