apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.13.1
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  tag: v3.0.3
                env:
                  REDIS_HOSTNAME: 'immich-valkey'
                  IMMICH_MACHINE_LEARNING_URL: 'http://immich-machine-learning:3003'
                  DB_HOSTNAME: "immich-postgres-rw"
                  DB_USERNAME: "immich"
                  DB_PASSWORD: "changeme123"
                  DB_DATABASE_NAME: "immich"
        immich:
          persistence:
            library:
              existingClaim: immich-pvc
        server:
          enabled: true
          service:
            main:
              type: LoadBalancer
        valkey:
          enabled: true
        machine-learning:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
