nextcloud:
  host: 192.168.1.50
  username: admin
  password: "114958701@"
  trustedDomains:
    - 192.168.1.50
    - 192.168.1.51
    - 192.168.1.52
    - 192.168.1.53
    - 10.42.0.0/16
  persistence:
    subPath:

internalDatabase:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: "114958701@"
        database: nextcloud
  primary:
    persistence:
      enabled: true

redis:
  enabled: true
  auth:
    password: "114958701@"

persistence:
  enabled: true
  existingClaim: nextcloud-pvc
  accessMode: ReadWriteMany

livenessProbe:
  enabled: false
  initialDelaySeconds: 120
readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 10
