---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-secret
  namespace: immich
spec:
  encryptedData:
    password: AgAoqtjq/xMUESDAPBC5cBufyrNMZkNL+gBLIAQEWkYBC+hk5u5HTfkp3UYbkdxR1Xgc4hjuDq3xzEAYaOSA2SMyc328/XzUzwYtS/VuQDEB4CZxzM4lZXbAQiJgZv9v+uBDZEdkT8YL5dAhGIqabCiYVdwaZyXvVuqQzs36Lx23wb0zqReeROFnnzSzgTKRuyEULPM1GjIhT9EzSYT97X+Om46XLIrk2AWw03hJrGc55jJPrPAp+pxiOUmJ83nQjr0FMkO9Q+kocyNA5Cf29A+AyEojlMz+JEvGgi37sUaE7BmXDvwWNCkLeCpEPjU3PgsiMmhcpKRxbiyIXz5a9Bi60U9Wy2G7I/b0+MKCazAv1sSUhfTN4CbcVBTh7Hid0UzTOhOuPjpHfIjCtE0XrwBLTwfPiUbjT79kUMiUUsKH1Wh+UljGvsA4yyj/NRxxrRnNOBIUgqEuaZPvv0wEFaV0r/uHiV0BoEL9qj2Vw8n59WPjENS6noTzgHeqJ4jMbS71gxNlW5alR9/i+FtZbZa/UN+ukgLdLFREmLM4AYIsFBiFWs8HTyiwVJW0/BKtDww2Z9w3getzpiMd5Fd1zqX3B2+4e95vH4nrPZludksgs+FT1xmpS4+SDe6zd0YEEA78BMWytX/kW8o6btha4+BkH/6VwHaXCNYWAPTiDWA8MZMiD2BZy2esm3IK0GrSVXg5rtetGm3EQZP2HsTSRCQLv44GRo5cx6MXJR4vPNSXfg==
    username: AgCgwORTSCE62S35lbnZdj9jBQYqQEQxrYAebWQW/9bFIR92bNocEwS62qMHdhwUF3HV4mohrAHaqCBFemQTOYLUe/iz0uf8XbG8+rTrm2059k+WlKYagWMbDFykSRvgL7QmZXdqHITIBJzf6p8c2wiCyVKAKmNf+c/WplNKUAfPEZBfmKbK46NutM8JYomT68yjAZtmK+SL8r7g6YmJ33AaMlAcP4sh/33oZcrh23XyA1jjIJfMDuqXQxmGSnhxPjC9AFyjQs2QeEUVoXfZPrs/Es5imMYlAw5FWOo+t3YNNQ5dFD4EnWPsYzD0/X/pFFcMsiniAUn12/U3AgsV1ZekiHL/hMQlyn3fKdrc7WRB1U1jUjW+sU4ZgIrZ86Ry7rSAlKaUpbepSB+kynuJIGuB7cHkzIC1sN07i3UeIxxvWtt+/9ZTNiaB1+x/dCDPNNnDFGIuDwC1SD7gu2Mm14OcpAPipIZi6Q1NA73yYKAGf7Ig0xkT2z687VzSyfzmnDb0n6KQ60tDBsCLyWz2CdxY0Qn26zIu6dxo1mfvX6houhCSeoc/zRJHqzfebl9MwklmOl6X8qe/0RLSJkBPXig/ymXcLU8GzjNu4GLkhMLHXPDe1f8HYVP2cZy7JWOMDI25sgh+6Qnbh2cO6Ov+1e6K00z3fl61Xh4ZYDn8CPSL7JhsNP25a72xsXXSTqf4+40muVu7T7s=
  template:
    metadata:
      name: immich-postgres-secret
      namespace: immich
    type: kubernetes.io/basic-auth
