---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-credentials
  namespace: immich
spec:
  encryptedData:
    password: AgDPrQsbTpA+ypnIzPefiwUYUCQRgqyN7IotvtlEdahVBSSTu/YObNeRyk/9vS23qGj8Ip6bs7CEQ3DBhMj8/ZMQSmLwIq7T8fiZUPYd+du6nQJS4pAbNwL79Htu5J4lrL6u3BYGyhep+w/A3C6fsZU2SWR77284b0nFXCHvTwMgm04Rqp46h3/M3A7QCNL4LJoyWSzqLJDPI4/+/fnPTvo/Ym0TAUZgqeahtMVq0ger75qrSeh/8brG7+rVL5NqHsDBaXAYJsbPJzkJE0pFSbs035Cc4WS7ZPBZ6qO2ssuIS6oeFCodqdQEKfe0v0eiSah6kCk0G3oGu0v7csWESxGGueEF/cgdWJGtA0notKqb/kOBsLSoL8zxjARwl7fKRSh7KIn44PVK5j/wghcMjtLUmrbb+Ggp+I96+hI5gNAaZqDimNNioPzkfGhjdwu4cFqk/loj14gHc8W1ap/voSQHBQttSgPH0GTtuUb2wFAfreyYp2WQHPp9qBqazI1vGXwHgDXv1p8ClIo5OxB1S7JtC4LBqWhPHZl1ZeBjn4/sK4TeX0+gtIDqjuAnSQcvdfIOtCtAoP73UW9pAslcNmHykYVwbrUdGLQMRRkqkf98vgEVmAbT66mGMAWoPK6GBxV2N5SQXjyByOL+wr8SOzQTJurLDnCdkAxIAZC0ZPag7vsILEDCvfVmbpVBJpDpJFCxpxTi7K+zlfmCZhmJevOxIbIImDzT5x4Qf+HnC3eRNw==
  template:
    metadata:
      name: immich-db-credentials
      namespace: immich
